### PR TITLE
Validate downloaded Zip file

### PR DESCRIPTION
**Pull request by antoineco**
Should fix the false positive you had with `assert_file`.

### CODE REVIEW

**Comment by typekpb** [comment]
@antoineco excelent, thanks!

**Comment by typekpb** [comment]
@antoineco would you be interested in becoming a collaborator of this repo? based on today's contributions you'd definitely deserve it.

**Comment by antoineco** [comment]
Well sure, if you want help in keeping it alive :+1: Hopefully Oracle doesn't fiddle with their SSO service too often :wink:

**Comment by typekpb** [comment]
thanks! invitation was sent

**Pull request merged**
